name: "Continuous Integration"

on: [push, pull_request]

jobs:
  phpunit:
    name: "PHPUnit"
    runs-on: "ubuntu-20.04"

    strategy:
      matrix:
        php-version:
          - "8.0"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"
        with:
          fetch-depth: 2

      - name: "Install PHP"
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          tools: composer:v2

      - name: Get Composer Cache Directories
        id: composer-cache
        run: |
          echo "::set-output name=files_cache::$(composer config cache-files-dir)"
          echo "::set-output name=vcs_cache::$(composer config cache-vcs-dir)"
      - name: Cache composer cache
        uses: actions/cache@v2
        with:
          path: |
            ${{ steps.composer-cache.outputs.files_cache }}
            ${{ steps.composer-cache.outputs.vcs_cache }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-
      - name: Run composer install
        run: composer install -ov
        env:
          COMPOSER_ROOT_VERSION: dev-master

      - name: "Run PHPUnit"
        run: "vendor/bin/phpunit --configuration phpunit.xml --coverage-clover=coverage.xml"

      - name: "Upload coverage file"
        uses: "actions/upload-artifact@v2"
        with:
          name: "phpunit-${{ matrix.php-version }}.coverage"
          path: "coverage.xml"

  upload_coverage:
    name: "Upload coverage"
    runs-on: "ubuntu-20.04"
    needs:
      - "phpunit"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"
        with:
          fetch-depth: 2

      - name: "Download coverage files"
        uses: "actions/download-artifact@v2"
        with:
          path: "reports"

      - name: "Send code coverage report to Codecov"
        uses: "codecov/codecov-action@v1"
        with:
          directory: reports

      - name: "Send code coverage report to Scrutinizer"
        run: |
          wget https://scrutinizer-ci.com/ocular.phar
          php ocular.phar code-coverage:upload --format=php-clover coverage.xml
